package com.revature.daos;

public class pomproperties {

}


/*

#Generated by Maven Integration for Eclipse
<<<<<<< HEAD
#Thu Jul 29 16:34:29 EDT 2021
m2e.projectLocation=C\:\\Users\\whatu\\Documents\\workspace-spring-tool-suite-4-4.8.1.RELEASE\\vcard\\backend\\PetShop
=======
#Thu Jul 29 15:52:57 CDT 2021
m2e.projectLocation=C\:\\Github\\JavaFS210601\\P3\\vcard\\backend\\PetShop
>>>>>>> 8b5eb87b6f3da31c09ca63b37d76d9e0cae3980d
m2e.projectName=PetShop
groupId=com.revature
artifactId=PetShop
version=0.0.1-SNAPSHOT

*/